name: Python application

on:
  schedule:
    - cron: '26 11 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install schedule
        pip install time
        
    - name: Update lanpang on bilibili
      run: |
        cd bilibili/lanpang
        sh run.sh
        
    - name: Update guodong on bilibili
      run: |
        cd bilibili/guodong
        sh run.sh
        
    - name: Update Refresh
      run: |
        sh run.sh
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
